In [1]:
import os
 #-----------------------------  open import ---------------------------------------#------ 
import cv2
import numpy as np
from numpy import array
import matplotlib.pyplot as plt
from skimage.io import imread,imshow
from skimage import measure,color,io,feature
from scipy.ndimage.morphology import binary_fill_holes
import matplotlib.patches as mpatches
from skimage.morphology import convex_hull_image
from skimage.measure import label, regionprops
import math
from scipy import ndimage as ndi
from skimage import feature
from skimage.filters import threshold_mean
from copy import copy,deepcopy
%matplotlib inline

In [2]:
x=[]
y=[]
path='C:/Users/Bermuda/OneDrive/Workshop/Dataset'
for fname in os.listdir(path):
#     print(fname,end=' ')
    paths=path+'/'+str(fname)
    for iname in os.listdir(paths):
        #print(iname,end=' ')
        pathss=paths+'/'+str(iname)
        img=imread(pathss)

        #convert rgb to hsv
        img_hsv=cv2.cvtColor(img,cv2.COLOR_RGB2HSV)

        #select green only
        img_green=deepcopy(img_hsv)

        img_green[:,:,0]=0
        img_green[:,:,2]=0

        #convert hsv green only to grayscale
        img_gray0=img_green[:,:,1]

        #thresholding
        ret,thresh = cv2.threshold(img_gray0,50,255,cv2.THRESH_BINARY)

        #morprology (dilation)
        kernel = cv2.getStructuringElement(cv2.MORPH_RECT,(3,3)) 
        dilation = cv2.dilate(thresh,kernel,iterations = 1)
        dilation[99:,:]=1
        dilation[30:60,99:]=1

        #fill holes
        filled_I = binary_fill_holes(dilation)
        filled_I[99:,:]=0  
        filled_I[30:60,99:]=0
        filled_I = filled_I*1
        
        im2,contours,h= cv2.findContours(filled_I,2,1)
        cnt = contours[0]
        hull = cv2.convexHull(cnt,returnPoints = False)
        hulla = cv2.convexHull(cnt,returnPoints = True)
        hullarea = cv2.contourArea(hulla)
        conarea = cv2.contourArea(cnt)
        defects = cv2.convexityDefects(cnt,hull)
        
        #find center
        M = cv2.moments(cnt)
        cx = int(M["m10"] / M["m00"])
        cy = int(M["m01"] / M["m00"])
        center = (cx,cy+10)
        cv2.circle(img,center,1,[255,0,0],-1)

        maxi = 0
        check = 0
        prelen=0
        count_i=0
        
        count_defects = 0
        count_finger = 0
        lena = [0,0,0,0]
        lenfinger = []
        anglelist = [0,0,0,0]
        
        #find defect
        for i in range(defects.shape[0]):
            s,e,f,d = defects[i,0]
            start = tuple(cnt[s][0])
            end = tuple(cnt[e][0])
            far = tuple(cnt[f][0])

            # find length of all sides of triangle
            #start to end
            a = math.sqrt((end[0] - start[0])**2 + (end[1] - start[1])**2)
            #start to defect
            b = math.sqrt((far[0] - start[0])**2 + (far[1] - start[1])**2)
            #defect to end
            c = math.sqrt((end[0] - far[0])**2 + (end[1] - far[1])**2)

            # apply cosine rule here
            angle = math.acos((b**2 + c**2 - a**2)/(2*b*c)) * 57

            #center to start check 1 
            longlen = math.sqrt((start[0] - cx)**2 + (start[1] - cy)**2)
            if longlen > maxi:
                maxi = longlen
                tip = start

            # ignore angles > 90 and highlight rest with red dots
            if angle <= 92:
                anglelist[count_i]=angle
                count_defects += 1
                cv2.circle(img, far, 1, [255,0,127], -1)
                #dist = cv2.pointPolygonTest(cnt,far,True)

                # draw a line from start to end i.e. the convex points (finger tips)
                # (can skip this part)

                cv2.line(img,start, end, [255,153,153], 2)
                cv2.circle(img, start, 1, [153,51,255], -1)
                cv2.circle(img, end, 1, [153,51,255], -1)
                lena[count_i]=a
                longlen1 = math.sqrt((start[0] - cx)**2 + (start[1] - cy)**2)
                longlen2 = math.sqrt((end[0] - cx)**2 + (end[1] - cy)**2)
                if count_defects == 1:
                    lenfinger.append(longlen1)
                    lenfinger.append(longlen2)
                    cv2.line(img,center,start,[255,0,0],1)
                    cv2.line(img,center,end,[255,0,0],1)
                    count_finger+=2
                else:
                    lenfinger.append(longlen2)
                    cv2.line(img,center,end,[255,0,0],1)
                    count_finger+=1
                count_i+=1
        if count_defects == 0:
            if tip[1]<cy:
                cv2.circle(img, tip, 1, [153,51,255], -1)
                cv2.line(img,center,tip,[255,0,0],1)
                count_finger+=1
                
        feature = [count_finger,count_defects,conarea/hullarea,anglelist[0],anglelist[1],anglelist[2],anglelist[3],lena[0],lena[1],lena[2],lena[3]]#count_finger,,count_defects,conarea/hullarea#anglelist,lena,center
        x.append(feature)
        y.append(fname)

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn import metrics
from sklearn import svm
from sklearn import linear_model
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.preprocessing import scale
from sklearn.preprocessing import StandardScaler, minmax_scale
x_norm = minmax_scale(x)


0.7736842105263158


In [54]:
#SVC

x_train, x_test, y_train, y_test = train_test_split(x_norm, y,test_size=0.3, random_state=507)
svc = svm.SVC(kernel='linear', C=10).fit(x_train, y_train)

x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)


loo = LeaveOneOut()
loo.split(x_train)

for train, test in loo.split(x_train):
    svc.fit(x_train[train], y_train[train])
    y_pred = svc.predict(x_train[test])
#     print("Accuracysvc:",metrics.accuracy_score(y_train[test], y_pred))

y_pred = svc.predict(x_test)
print("Accuracysvc:",metrics.accuracy_score(y_test, y_pred))    
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

Accuracysvc: 0.9122807017543859
[[7 1 0 0 0 0 0 0 0 0]
 [0 8 1 0 0 0 0 0 0 0]
 [0 0 6 0 0 0 0 0 0 0]
 [0 0 0 8 0 0 0 0 0 0]
 [0 0 0 0 2 0 1 0 0 0]
 [0 0 0 0 0 7 0 0 0 0]
 [0 0 0 0 0 0 4 0 0 1]
 [0 0 0 0 0 0 0 8 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 2]]
             precision    recall  f1-score   support

          0       1.00      0.88      0.93         8
          1       0.89      0.89      0.89         9
          2       0.86      1.00      0.92         6
          3       0.89      1.00      0.94         8
          4       1.00      0.67      0.80         3
          5       1.00      1.00      1.00         7
          6       0.80      0.80      0.80         5
          7       1.00      1.00      1.00         8
          8       0.00      0.00      0.00         1
          9       0.67      1.00      0.80         2

avg / total       0.91      0.91      0.90        57



C:\Users\Bermuda\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [47]:
#MLP neural network

from sklearn.model_selection import LeaveOneOut
x_train, x_test, y_train, y_test = train_test_split(x_norm, y,test_size=0.3, random_state=1)
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                         hidden_layer_sizes=(6, 59), random_state=507)
#np.array can call array fill index array background C 
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)

loo = LeaveOneOut()
loo.split(x_train)
for train, test in loo.split(x_train):
    clf.fit(x_train[train], y_train[train])
    y_pred = clf.predict(x_train[test])
#     print("Accuracysvc:",metrics.accuracy_score(y_train[test], y_pred))

y_pred = svc.predict(x_test)
print("Accuracysvc:",metrics.accuracy_score(y_test, y_pred)) 
#     print(confusion_matrix(y_test, y_pred))  
#     print(classification_report(y_test, y_pred))

Accuracysvc: 0.8596491228070176
